# Generated by Django 6.0.3 on 2026-03-25 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('A', 'Part-A (1 Mark)'), ('B', 'Part-B (2 Marks)'), ('C', 'Part-C (3 Marks)')], max_length=1)),
                ('co', models.CharField(choices=[('CO1', 'CO1'), ('CO2', 'CO2'), ('CO3', 'CO3')], max_length=3)),
                ('btl', models.IntegerField(choices=[(1, 'BTL-1 Remember'), (2, 'BTL-2 Understand'), (3, 'BTL-3 Apply'), (4, 'BTL-4 Analyze'), (5, 'BTL-5 Evaluate'), (6, 'BTL-6 Create')])),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='papers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=50)),
                ('exam_type', models.CharField(default='MID TERM EXAMINATION, EVEN SEMESTER', max_length=100)),
                ('session', models.CharField(default='2025-26', max_length=20)),
                ('duration', models.CharField(default='1 Hour', max_length=50)),
                ('max_marks', models.IntegerField(default=20)),
                ('instructions', models.TextField(default='Attempt all parts given in the question paper. No student is allowed to leave the examination hall before the completion of the time.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='papers', to='papers.question')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.subject')),
            ],
        ),
    ]
